// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

// Code generated by snarkjs zkey export solidityverifier
// Example for illustration — use your own generated file!

contract Verifier {
    function verifyProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[] memory input
    ) public view returns (bool r) {
        // <Your generated verifying key and logic here>
        // This is where snarkjs puts all the cryptographic operations.
        r = true; // stub for illustration
    }
}
